-define(ALPN_HTTP1, <<"http/1.1">>).
-define(ALPN_HTTP2, <<"h2">>).
-define(ALPN_SPDY1, <<"spdy/1">>).
-define(ALPN_SPDY2, <<"spdy/2">>).
-define(ALPN_SPDY3, <<"spdy/3">>).
-define(ALPN_HEROKU_TCP, <<"htcp1">>).
